name: build

on:
  push:
    branches:
      - main

jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setting up node_modules and angular-cli
        run: |
          echo Initiating angular-cli installation v9.1.3..........
          npm install @angular/cli@9.1.3
          echo Initiating node_modules installation..............
          npm install
          echo Initiating Build............
          npm run build:prod
          git config --global user.name "padmesh97"
          git config --global user.email "kunwarpadmesh@yahoo.com"
          git add .
          git commit -m "commit"
          echo Build created successfully..................

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp://ftpupload.net/htdocs
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/synflow
          server-dir: synflow/